# Generated by Django 3.0.7 on 2020-06-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meal_type',
            field=models.CharField(default='entree', max_length=50),
            preserve_default=False,
        ),
    ]
