# Generated by Django 3.0.7 on 2020-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_item_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=9.99),
            preserve_default=False,
        ),
    ]
